Enable Solr On PSH
Vardot/platformsh-varbase9 pull request #3
Opened 2020-12-16 23:26 UTC by AhmadMari

2021-01-04 09:37 UTC, Natshah commented
Please comment in

- .platform.app.yaml
- .platform/services.yaml
- docroot/sites/default/settings.platformsh.php

As not all projects will use solr
We need them to be uncommented when needed

But keep files in .platform/solr_8.x_config/

Maybe a documentation page could follow to explain the steps to activate solr in varbase-project

2021-01-04 09:56 UTC, moerazem commented on .platform.app.yaml
> +    solrsearch: 'search:main'
I prefer this to be renamed according to PSH documentation. See https://docs.platform.sh/configuration/services/solr.html#usage-example
For example: `solrsearch: "searchsolr:solr"`

Also, let's keep this commented as we do not want it to be enabled by default. But this would be a good template for the project that has Solr.

2021-01-04 09:56 UTC, moerazem commented on .platform/services.yaml
> +search:
This would also be renamed according to the name of the relationship.
Also, this block should be commented as explained above.

2021-01-04 09:56 UTC, moerazem commented on .platform/services.yaml
> +            main:
This would also be renamed according to the name of the relationship.
Also, this block should be commented as explained above.

2021-01-04 09:56 UTC, moerazem commented on docroot/sites/default/settings.platformsh.php
> +$platformsh = new \Platformsh\ConfigReader\Config();
This is good. No need need to comment this block since it will NOT work unless the service is running.

2021-01-04 09:56 UTC, moerazem commented on docroot/sites/default/settings.platformsh.php
> +//SOLR setup config https://docs.platform.sh/frameworks/drupal8/solr.html
Comments should have a space between `//` and the text start.

2021-01-04 12:08 UTC, AhmadMari commented on .platform.app.yaml
> +    solrsearch: 'search:main'
Done

2021-01-04 12:08 UTC, AhmadMari commented on .platform/services.yaml
> +search:
Done

2021-01-04 12:08 UTC, AhmadMari commented on docroot/sites/default/settings.platformsh.php
> +$platformsh = new \Platformsh\ConfigReader\Config();
Done

2021-01-04 12:08 UTC, AhmadMari commented on docroot/sites/default/settings.platformsh.php
> +//SOLR setup config https://docs.platform.sh/frameworks/drupal8/solr.html
Done

2021-01-04 12:09 UTC, AhmadMari commented on .platform/services.yaml
> +            main:
Done

2021-01-04 12:52 UTC, Natshah submitted a review, later dismissed

2021-01-07 17:33 UTC, Natshah requested changes

2021-01-07 17:33 UTC, Natshah commented on docroot/sites/default/settings.platformsh.php
> +use Drupal\Core\Installer\InstallerKernel;
the
`use Drupal\Core\Installer\InstallerKernel;`
is listed in line number 8 
https://github.com/AhmadMari/platformsh-varbase/blob/master/docroot/sites/default/settings.platformsh.php

2021-01-10 07:09 UTC, moerazem approved these changes
All code additions look good.

2021-01-10 07:11 UTC, moerazem commented
From my side all look good.
@Natshah please check and approve if there's nothing else from your end.

@AhmadMari I just need you to confirm also that you tested these two scenarios:

- [ ] Test the project creation with comments | New Varbase must install, Solr is not provisioned
- [ ] Test the project creation after you remove comments | Solr should be connected

2021-01-10 11:42 UTC, AhmadMari commented on docroot/sites/default/settings.platformsh.php
> +use Drupal\Core\Installer\InstallerKernel;
Done, please consider my latest changes on settings.platformsh.php file

2021-01-10 11:50 UTC, AhmadMari commented
@moerazem @Natshah 
The project has been tested on both scenarios with and without Solr configuration

2021-01-10 11:52 UTC, merged

2021-01-10 11:54 UTC, Natshah reviewed
Approved and Squash and merge
Thank you :+1: